# maybe -fno-common

CFLAGS += -marm -mcpu=arm7tdmi-s -fwrapv -freg-struct-return -fno-stack-limit -I$(SOCDIR) \
	-ffunction-sections

AFLAGS += -mcpu=arm7tdmi-s -mapcs-32

SOC_SRCS = lpc_i2c.cpp lpc_uart.cpp lpc_timer.cpp lpc_spi.cpp  lpc_vic.cpp

SRCS += $(addprefix $(SOCDIR)/,$(SOC_SRCS))

ODIR_TREE += $(ODIR)/$(SOCDIR)
