SOC_SRCS = timer.cxx dma.cxx eeprom.cxx sdmmc.cxx # adc.cxx spi.cxx ethernet.cxx 

SRCS += $(addprefix $(SOCDIR)/stm32h7x/,$(SOC_SRCS))

ODIR_TREE += $(ODIR)/$(SOCDIR)/stm32h7x

ARCH=$(ENETCORE)/arch/armv7m

include $(ARCH)/makefile.$(TOOLSET)
