# -*- Makefile -*-
# Copyright (c) 2018-2021 Jan Brittenson
# See LICENSE for details.

# Set up tools, add board peripherals and SOC components to build
#include $(BOARD)/makefile.$(TOOLSET)

CFLAGS += -I$(ENETCORE)/ui

UI_SRCS = ui.cxx

SRCS += $(addprefix $(ENETCORE)/ui/,$(UI_SRCS))

ODIR_TREE += $(ODIR)/$(ENETCORE)/ui
