# -*- Makefile -*-
# Copyright (c) 2018-2021 Jan Brittenson
# See LICENSE for details.

# Set up tools, add board peripherals and SOC components to build
#include $(BOARD)/makefile.$(TOOLSET)

UIDIR=$(ENETCORE)/ui
CFLAGS += -I$(UIDIR)

UI_SRCS = ui.cxx

SRCS += $(addprefix $(UIDIR)/,$(UI_SRCS))

ODIR_TREE += $(ODIR)/$(UIDIR)
